### ISSUE TITLE
Local functions causes compilation failed

### ISSUE THREAD

**Issue by Matthiee** [stryker-mutator/stryker-net#321]
Compilation fails when using local functions in 0.8.1.
If I remove the local functions everything works as expected.

```
[07:56:24 DBG] The name 'MyLocalFunction' does not exist in the current context
[07:56:24 ERR] Failed to restore the project to a buildable state. Please report the issue. Stryker can not proceed further
[07:56:24 ERR] An error occurred during the mutation test run
System.ApplicationException: Failed to restore build able state.
   at Stryker.Core.Compiling.CompilingProcess.Compile(IEnumerable`1 syntaxTrees, MemoryStream ms, Boolean devMode)
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate(StrykerOptions options)
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options)
```

**Comment by Mobrockers** [comment]
I don't think we changed anything about the compile process since 0.8.0. Could you give us some reproducible sample code so we can investigate? Also could you confirm it did work on 0.8.0 or earlier?

**Comment by Matthiee** [comment]
Hi @Mobrockers 

I can confirm it did **NOT** work in 0.8.0 release. 

Here is a link to the repo for reproduction. 

https://github.com/Matthiee/Playground/tree/stryker

**Comment by Matthiee** [comment]
@richardwerkman It works for me with #325

**Comment by Mobrockers** [comment]
I have started the release for 0.8.2 which includes the fix
